{{ if .Values.appsettings }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "web-application.fullname" . }}-appsettings
data:
  appsettings.json: |-
    {{- toJson ( .Values.appsettings ) | nindent 8}}
{{end}}
