apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-application.fullname" . }}
  labels:
    {{- include "web-application.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "web-application.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "web-application.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "web-application.serviceAccountName" . }}
      {{- if .Values.volumes }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8}} 
      {{ end }}   
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
             {{- if .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12}} 
          {{ end }}   
          env: 
          {{- if eq .Values.mongodb.enabled true }} 
            - name: MONGO_PORT
              value:  "27017"
            - name: MONGO_URL
              value:  mongodb://{{.Values.mongodb.auth.rootUser}}:{{.Values.mongodb.auth.rootUser}}@{{.Release.Name}}-mongodb
            - name: MONGO_HOST
              value:  {{.Release.Name}}-mongodb
            - name: MONGO_USER
              value: root
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{.Release.Name}}-mongodb
                  key: mongodb-root-password
            {{ end }}
          {{- if .Values.env }}{{ toYaml .Values.env | nindent 12}} {{ end }}  
         
       
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports: {{if .Values.ports }}{{ toYaml .Values.ports | nindent 12}} {{ end }} 
          livenessProbe: {{if .Values.livenessProbe }}{{ toYaml .Values.livenessProbe | nindent 12}} {{ end }} 
          readinessProbe: {{if .Values.readinessProbe }}{{ toYaml .Values.readinessProbe | nindent 12}} {{ end }} 
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
