# This is a basic workflow to help you get started with Actions

name: CI
env:
  package: 'web-application'
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
    - '${{ env.package }}/**'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      
      - name: Helm tool installer
        uses: Azure/setup-helm@v2.0
      
      - name: create package folder 
        run: mkdir -p ./packages
      
      # Runs a single command using the runners shell
      - name: helm dependency update ./web-application
        run: helm dependency update ./web-application
       
      # Runs a single command using the runners shell
      - name: helm package ./web-application 
        run: helm package ./web-application -d packages
       
      # Runs a set of commands using the runners shell
      - name: git upload
        run: |
          git config --global user.email "info@cliap,de"
          git config --global user.name "RELEASE PIPELINE"
          git add .
          git commit -m "release creation"
          git push
